Algoritmo "semnome"
// Algoritmos
// Santos L. Victor 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/06/2020
arquivo "teste.txt"

Var
// Seção de Declarações das variáveis 
   x:inteiro
   y:caracter
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   para x de 1 ate 5 faca
      escreval("digite")
      leia (y)
   fimpara

Fimalgoritmo